name: Continuous Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - run: pnpm install
    - run: pnpm build
    - run: pm2 restart ecosystem.config.cjs
